/* This file is automatically generated based on your hardware design. */
#include "memory_config.h"

struct memory_range_s memory_ranges[] = {
	/* axi_bram_ctrl_1_Mem0 memory will not be tested since application resides in the same memory */
	/* microblaze_0_local_memory_dlmb_bram_if_cntlr_Mem memory will not be tested since application resides in the same memory */
	{
		"ps7_ddr_0_C_GP0_AXI_BASENAME",
		"ps7_ddr_0",
		0x00100000,
		1072693248,
	},
	{
		"ps7_ram_0_C_GP0_AXI_BASENAME",
		"ps7_ram_0",
		0x00000050,
		262064,
	},
};

int n_memory_ranges = 2;
